
-- ENSURE ALL COLUMNS EXIST IN EMPLOYEES
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS name_arabic TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS department_arabic TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS position_arabic TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS face_token TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS device_user_id TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'Employee';
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS civil_id_expiry TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS pifss_number TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS passport_number TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS passport_expiry TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS izn_amal_expiry TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS iban TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS bank_code TEXT DEFAULT 'NBK';
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS manager_id TEXT;
ALTER TABLE IF EXISTS employees ADD COLUMN IF NOT EXISTS manager_name TEXT;

-- RELOAD SCHEMA
NOTIFY pgrst, 'reload schema';
